services:
  ocbconfig:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: ['deno', 'task', 'prod']
    environment:
      # - DIST_MODULE=
      - DIST_NAME="Hello ocbConfig"
      - DIST_DESCRIPTION="OpenTelemetry Collector, build with the help of ocbConfig"
      # - DIST_VERSION=
      # - DIST_OUTPUT_PATH=
